\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{discrete}

\LoadClass{article}

\RequirePackage[top=0.5in,left=0.9in,bottom=0.9in,right=0.9in]{geometry}
\RequirePackage{amssymb,amsmath,amsthm,latexsym}
\RequirePackage[english]{babel}
\RequirePackage{fitch}

\title{COMP 256 -\ FA2020}
\author{Philip Kim}

\newtheorem{theorem}{Theorem}[section]
\newtheorem{corollary}{Corollary}[theorem]
\newtheorem{prove}[theorem]{Prove}
